# GRAB THE LATEST NODEJS IMAGE
FROM node:latest

# CREATING THE USER AND ADD THE USER INTO THE CONTEXT DOCKER GROUP
RUN useradd --user-group --create-home --shell /bin/false app

# SET UP THE HOME ENV WITH PACKAGES
ENV HOME=/home/app
COPY package.json $HOME/
RUN chown -R app:app $HOME/*

# DEFINE THE USER ROOT AND SETUP THE HOMEDIR
USER root
WORKDIR $HOME

# INSTALLING THE ADONIS GLOBALLY
RUN npm i -g @adonisjs/cli

# INSTALLING THE PACKAGE DEPEDENCIES
RUN yarn install
